services:
  desadoor-api:
    build:
      context: .
      dockerfile: Desadoor.Api/Dockerfile
    container_name: desadoor-api
    ports:
      - "5015:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DESADOOR_JWT_KEY=${DESADOOR_JWT_KEY:-DesadoorGizliAnahtar2024!Guvenliyir#XYZ987}
      - VeriTabani__Yol=/app/Veri/desadoor_v2.db
    volumes:
      - desadoor_data_v2:/app/Veri
    restart: unless-stopped

  desadoor-ui:
    build:
      context: .
      dockerfile: Desadoor.UI/Dockerfile
    container_name: desadoor-ui
    ports:
      - "5013:80"
    depends_on:
      - desadoor-api
    restart: unless-stopped

volumes:
  desadoor_data_v2:
