// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VizitLink3D.Konfigurator.Api.VeriTabani;

#nullable disable

namespace VizitLink3D.Konfigurator.Api.VeriTabani.Migrations
{
    [DbContext(typeof(KonfiguratorDbContext))]
    [Migration("20260721161046_UcBoyutModelParcalariEklendi")]
    partial class UcBoyutModelParcalariEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("VizitLink3D.Konfigurator.Api.Moduller.Kimlik.Modeller.KonfiguratorKullanicisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Eposta")
                        .IsUnique();

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("VizitLink3D.Konfigurator.Api.Moduller.Kimlik.Modeller.SifreSifirlamaIstegi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("KullanildiMi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("KullanilmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("TokenHash");

                    b.ToTable("SifreSifirlamaIstekleri");
                });

            modelBuilder.Entity("VizitLink3D.Konfigurator.Api.Moduller.Modeller.Modeller.UcBoyutModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BoyutBayt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DosyaAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("IcerikTuru")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("UcBoyutModeller");
                });

            modelBuilder.Entity("VizitLink3D.Konfigurator.Api.Moduller.Modeller.Modeller.UcBoyutModelParcasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GorunenAd")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("GorunurMu")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeshAdi")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParcaTuru")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RenkDegistirilebilirMi")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("VarsayilanMalzeme")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("VarsayilanRenk")
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelId", "MeshAdi")
                        .IsUnique();

                    b.ToTable("UcBoyutModelParcalari");
                });

            modelBuilder.Entity("VizitLink3D.Konfigurator.Api.Moduller.Kimlik.Modeller.SifreSifirlamaIstegi", b =>
                {
                    b.HasOne("VizitLink3D.Konfigurator.Api.Moduller.Kimlik.Modeller.KonfiguratorKullanicisi", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("VizitLink3D.Konfigurator.Api.Moduller.Modeller.Modeller.UcBoyutModelParcasi", b =>
                {
                    b.HasOne("VizitLink3D.Konfigurator.Api.Moduller.Modeller.Modeller.UcBoyutModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });
#pragma warning restore 612, 618
        }
    }
}
