@KonfiguratorApi_HostAddress = http://localhost:5116

### Saglik kontrolu
GET {{KonfiguratorApi_HostAddress}}/saglik
Accept: application/json

###

### Giris
POST {{KonfiguratorApi_HostAddress}}/api/kimlik/giris
Content-Type: application/json

{
  "kullaniciAdi": "admin",
  "sifre": "Admin123!"
}

###
