<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>VizitLink3D.Konfigurator</RootNamespace>
    <UserSecretsId>355739b0-4a5e-418f-b2cc-888d9c74bd18</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="VizitLink3D.Testler" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="8.*" />
  </ItemGroup>

</Project>
