<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <WasmDebugLevel>0</WasmDebugLevel>
    <BlazorEnableCompression>true</BlazorEnableCompression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CodeBeam.MudBlazor.Extensions" Version="9.1.0" />
    <PackageReference Include="FormCraft" Version="2.5.0" />
    <PackageReference Include="Gotho.BlazorPdf.MudBlazor" Version="2.2.0" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.Blazor" Version="2.0.0-rc4.5" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.7" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.7" />
    <PackageReference Include="MudBlazor" Version="9.4.0" />
    <PackageReference Include="MudBlazor.Extensions" Version="9.4.0" />
    <PackageReference Include="MudBlazor.ThemeManager" Version="4.0.0" />
    <PackageReference Include="MudExRichTextEditor" Version="9.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Desadoor.Ortak\Desadoor.Ortak.csproj" />
  </ItemGroup>

</Project>
